### ISSUE TITLE
Change navigation bar?

### ISSUE THREAD

**Issue by ghburdie** [plutus-community/docs#19]
My suggestion:

Navigation bar for [Plutus Community Docs](https://plutus-community.readthedocs.io) should be shortened and the most recent posts should appear at the top.

I'm working on changing navigation. I'll be making a pull request for it soon.
Here are some graphics roughly showing the proposed changes (recently added documents are not included yet):

[Navigation Proposal Part 1](https://drive.google.com/file/d/1bP-4_BlN8ELY_UsRiUasmTCsWpddiagD/view?usp=sharing), [Navigation Proposal Part 2](https://drive.google.com/file/d/1TboGfZUoUKGH228uydIcuFHNBm3ukJ6L/view?usp=sharing)

**Comment by jmhoms** [comment]
First all thanks for the suggestions and for taking the time to put together the big PR that was merged yesterday.  As you may have noted, since then, the documentation failed to build, so some errors were shown given the changes in the file structure.  I invested many hours today fixing all the issues, so the documentation site has been finally updated with many of the changes you proposed. Fortunately we’re not doing big changes often, but certainly we’ll need to improve the discussion and review process before doing the merges.

Personally, I don’t agree with some of the already merged changes you proposed, see below some tweaks I did and others I propose, of course everything is open for discussion (even if a bit late this time).

- We were using the automatic indexing of mkdocs to simplify the process and to not have to maintain the index. I agree that with the increase of content, manually defining the nav gives us more control on the way to show the information. Be aware that some articles may be now not referenced, I’ll double check it later. On the other hand I’ll make sure everyone’s is on the same page as the procedure to post new content slightly changed. 
- I fixed some requirements to avoid what  looks like a Jinja2 bug with mkdocs that was generating an error at build time when defining the nav. For reference: https://github.com/mkdocs/mkdocs/issues/2799
- I changed the readthedocs theme for the windmill one, as it was indeed too cluttered with the limit of 2 in depth and the nesting behaving weirdly. In my opinion this solves great part of the problem, so I’d come back to include the links to the documents directly in the nav instead of listing them in dedicated pages.
- I changed back the ordering of the lectures, because with the nesting features working correctly, I think that it makes more sense to see the indexed content in chronological order (I see the inverse order more suitable for a blog).
- I’d rename Open_Source_Cardano_Projects to Related, to open the scope.
- I’d rename Outdated_Material to Outdated, and change the deprecated category also to outdated, as I think it is more accurate.
- I’d move the Guides directory to the Docs root (from inside Environment), also I’d use Guides in the nav instead of “How Tos”.

Everyone, inputs are welcome!

**Comment by ghburdie** [comment]
Thank you for your efforts!

The navigation of the windmill theme is more pleasing than the one of readthedocs.

You now have not to scroll so much to go to the item you are looking for.

So the order of the items is not so important anymore as before although I still think, that the most recent cohort should be at the top in the Lectures section (what would be the order if we had 10 cohorts?). But this should not become a question of live or death.

**Comment by Totes5706** [comment]
Things are looking much cleaner! Thanks for the submission.

**Comment by jmhoms** [comment]
> So the order of the items is not so important anymore as before although I still think, that the most recent cohort should be at the top in the Lectures section (what would be the order if we had 10 cohorts?). 

You're right considering infinite growing lists, which is not the case for the chapters of each cohort, but certainly we could invert the order of the different cohorts. In any case, IMHO at some point it'll make more sense to list the old ones in a summary page and only keep the last X in the navigation menu, because beyond the navigation issues, the information of old cohorts will become somehow obsolete after some time. 

Cheers!

**Comment by jmhoms** [comment]
All the changes proposed are available on the latest version.
